version: '3'

services:
  discovery-server:
    image: mplescano/avatar-citizen-server-discoverer
    container_name: discovery-server
    hostname: discovery-server
    networks: 
      - cluster-network
    ports:
     - 8761:8761

  logging-server:
    image: mplescano/avatar-citizen-server-logging
    container_name: logging-server
    hostname: logging-server
    depends_on:
      - discovery-server
    ports:
     - 9411:9411
    networks: 
      - cluster-network

  database:
    image: mplescano/avatar-citizen-server-database
    container_name: database
    hostname: database
    networks: 
      - cluster-network
    ports:
     - 9002:9002

  api-core-service:
    image: mplescano/avatar-citizen-server-api-core
    container_name: api-core-service
    hostname: api-core-service
    depends_on:
      - discovery-server
      - logging-server
      - database
    networks: 
      - cluster-network

  gateway:
    image: mplescano/avatar-citizen-server-gateway
    container_name: gateway
    hostname: gateway
    depends_on:
      - discovery-server
    networks: 
      - cluster-network

networks:
  cluster-network:
    driver: bridge