
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (1, 'Damaris Deeson', 183, 67, 'Goldenrod', 'Female', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (2, 'Mack De Giorgio', 167, 115, 'Red', 'Male', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (3, 'Sammy Robins', 197, 64, 'Aquamarine', 'Male', 'Bespin');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (4, 'Wilt Murtimer', 170, 96, 'Green', 'Male', 'Bespin');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (5, 'Lulu Vanyushin', 176, 68, 'Crimson', 'Female', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (6, 'Sasha Corps', 153, 117, 'Crimson', 'Female', 'Alderaan');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (7, 'Konstantine Stickland', 185, 81, 'Indigo', 'Male', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (8, 'Hedvig Mildenhall', 196, 116, 'Mauv', 'Female', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (9, 'Amye Camps', 188, 57, 'Red', 'Female', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (10, 'Frazer Bolzen', 157, 58, 'Blue', 'Male', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (11, 'Sonnie Manie', 150, 92, 'Red', 'Male', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (12, 'Corissa Uphill', 189, 102, 'Indigo', 'Female', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (13, 'Catha Stiegars', 193, 55, 'Purple', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (14, 'Karlyn Putton', 182, 82, 'Khaki', 'Female', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (15, 'Ellene Burger', 169, 59, 'Orange', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (16, 'Arlette Freund', 164, 64, 'Blue', 'Female', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (17, 'Ema Gylle', 167, 60, 'Orange', 'Female', 'Alderaan');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (18, 'Hillary Beckson', 197, 75, 'Turquoise', 'Female', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (19, 'Sabrina Annable', 170, 79, 'Puce', 'Female', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (20, 'Derry Oliffe', 162, 81, 'Turquoise', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (21, 'Ramon Pedracci', 166, 116, 'Purple', 'Male', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (22, 'Gilly Salatino', 171, 119, 'Green', 'Female', 'Alderaan');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (23, 'Raymund Dubery', 151, 70, 'Violet', 'Male', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (24, 'Westley Dinnage', 157, 78, 'Goldenrod', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (25, 'Aurelia Peevor', 172, 112, 'Aquamarine', 'Female', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (26, 'Shauna Margerison', 183, 54, 'Maroon', 'Female', 'Alderaan');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (27, 'Alden Gracewood', 185, 96, 'Crimson', 'Male', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (28, 'Janeta Gummow', 183, 109, 'Pink', 'Female', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (29, 'Emmey Sherreard', 167, 77, 'Violet', 'Female', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (30, 'Nanice Bramer', 154, 105, 'Green', 'Female', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (31, 'Clint Oswald', 161, 56, 'Green', 'Male', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (32, 'Beulah Worner', 179, 89, 'Purple', 'Female', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (33, 'Carolina Jessen', 178, 50, 'Indigo', 'Female', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (34, 'Dottie Burkart', 195, 82, 'Green', 'Female', 'Bespin');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (35, 'Obidiah Verbrugge', 177, 85, 'Turquoise', 'Male', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (36, 'Kizzee Yarrow', 182, 112, 'Goldenrod', 'Female', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (37, 'Burton Janczewski', 197, 107, 'Red', 'Male', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (38, 'Nora Trainer', 165, 74, 'Maroon', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (39, 'Cyril Clunan', 187, 59, 'Khaki', 'Male', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (40, 'Cornie Whitty', 163, 118, 'Turquoise', 'Male', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (41, 'Charyl Shipston', 164, 98, 'Pink', 'Female', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (42, 'Hagan Bradforth', 185, 92, 'Goldenrod', 'Male', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (43, 'Bibby Halt', 178, 86, 'Aquamarine', 'Female', 'Alderaan');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (44, 'Munroe Hoys', 177, 100, 'Mauv', 'Male', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (45, 'Alexander Schout', 176, 77, 'Yellow', 'Male', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (46, 'Gonzalo Matzaitis', 173, 81, 'Aquamarine', 'Male', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (47, 'Alene Pirazzi', 170, 82, 'Aquamarine', 'Female', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (48, 'Ciro Meddick', 182, 61, 'Green', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (49, 'Trip Crossfield', 159, 65, 'Mauv', 'Male', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (50, 'Maurice Foort', 155, 120, 'Purple', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (51, 'Elfrieda Isacke', 167, 117, 'Maroon', 'Female', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (52, 'Novelia Ecclestone', 182, 95, 'Aquamarine', 'Female', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (53, 'Helaina Waiting', 196, 79, 'Mauv', 'Female', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (54, 'Berget Willets', 178, 80, 'Maroon', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (55, 'Ludvig Attock', 197, 89, 'Red', 'Male', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (56, 'Deane Layzell', 186, 56, 'Green', 'Male', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (57, 'Burt Copnall', 190, 79, 'Turquoise', 'Male', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (58, 'Sawyer McHaffy', 162, 55, 'Purple', 'Male', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (59, 'Ogden Duxfield', 162, 109, 'Blue', 'Male', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (60, 'Bradly Kopman', 155, 57, 'Aquamarine', 'Male', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (61, 'Odessa Colleton', 153, 98, 'Red', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (62, 'Raina Crampsy', 191, 95, 'Fuscia', 'Female', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (63, 'Leilah Audus', 191, 58, 'Orange', 'Female', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (64, 'Calv Crookes', 182, 60, 'Pink', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (65, 'Ciro Gomm', 173, 63, 'Turquoise', 'Male', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (66, 'Rene Casemore', 178, 112, 'Maroon', 'Male', 'Bespin');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (67, 'Caz Vaen', 175, 116, 'Goldenrod', 'Male', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (68, 'Amil Waldrum', 159, 86, 'Aquamarine', 'Female', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (69, 'Coreen Horick', 162, 92, 'Purple', 'Female', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (70, 'Walsh McKerlie', 184, 119, 'Turquoise', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (71, 'Marv Van den Broek', 155, 118, 'Green', 'Male', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (72, 'Kathryne Langthorn', 187, 94, 'Violet', 'Female', 'Bespin');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (73, 'Isidor Gert', 152, 54, 'Crimson', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (74, 'Nikolos Camfield', 158, 101, 'Green', 'Male', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (75, 'Ingeborg Tzuker', 162, 111, 'Aquamarine', 'Female', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (76, 'Harri Moreland', 158, 78, 'Green', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (77, 'Abbe Valerio', 177, 109, 'Maroon', 'Male', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (78, 'Elston Behnecken', 162, 54, 'Red', 'Male', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (79, 'Erich Loveard', 169, 78, 'Puce', 'Male', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (80, 'Nappy Bonwick', 163, 83, 'Blue', 'Male', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (81, 'Binny Blaik', 188, 83, 'Purple', 'Female', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (82, 'Dolly Lordon', 184, 109, 'Mauv', 'Female', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (83, 'Clio Jepp', 189, 107, 'Turquoise', 'Female', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (84, 'Aleda Fowle', 196, 105, 'Pink', 'Female', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (85, 'Rochell Josuweit', 180, 56, 'Khaki', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (86, 'Morlee Gerauld', 191, 68, 'Maroon', 'Male', 'Geonosis');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (87, 'Amitie Hattoe', 179, 65, 'Orange', 'Female', 'Dagobah');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (88, 'Rodrick Studd', 197, 118, 'Pink', 'Male', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (89, 'Eliza Simeons', 185, 70, 'Fuscia', 'Female', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (90, 'Dimitri Braizier', 156, 95, 'Goldenrod', 'Male', 'Naboo');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (91, 'Devonna Seivertsen', 175, 118, 'Pink', 'Female', 'Alderaan');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (92, 'Ralph Sayburn', 151, 71, 'Crimson', 'Male', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (93, 'Marice Caudwell', 150, 94, 'Violet', 'Female', 'Kamino');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (94, 'Anders Luchelli', 180, 82, 'Maroon', 'Male', 'Bespin');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (95, 'Dalis Welbourn', 192, 97, 'Crimson', 'Male', 'Yavin IV');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (96, 'Orella Rowles', 168, 105, 'Maroon', 'Female', 'Bespin');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (97, 'Simonette Eilles', 151, 95, 'Pink', 'Female', 'Coruscant');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (98, 'Bartholomeo Gunny', 170, 87, 'Fuscia', 'Male', 'Endor');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (99, 'Marmaduke Restieaux', 188, 67, 'Fuscia', 'Male', 'Hoth');
insert into citizens (id, name, height, mass, hair_color, gender, planet) values (100, 'Jillayne Hadlow', 178, 74, 'Khaki', 'Female', 'Kamino');
